export const chefs = [
    {
        id: 1,
        image: "/images/chef-1.png",
        firstName: "Aziz",
        lastName: "Karimov",
        age: 46,
        experience: "20 Years",
        rating: 4.9,
    },
    {
        id: 2,
        image: "/images/chef2.png",
        firstName: "Jasur",
        lastName: "Rahmonov",
        age: 32,
        experience: "15 Years",
        rating: 4.8,
    },
    {
        id: 3,
        image: "/images/chef-3.png",
        firstName: "Bekzod",
        lastName: "Tursunov",
        age: 28,
        experience: "10 Years",
        rating: 5.0,
    },
    {
        id: 4,
        image: "/images/chef-4.png",
        firstName: "Sardor",
        lastName: "Yuldashev",
        age: 24,
        experience: "8 Years",
        rating: 4.7,
    },
];